### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by wipatrick** [smueller18/flink-serialization#11]
I run into the following exception:

```java
java.lang.NullPointerException
	at com.github.smueller18.flink.serialization.AvroBuilderKeyedSerializationSchema.serializeKey(AvroBuilderKeyedSerializationSchema.java:63)
	at com.github.smueller18.flink.serialization.AvroBuilderKeyedSerializationSchema.serializeKey(AvroBuilderKeyedSerializationSchema.java:35)
	at org.apache.flink.streaming.connectors.kafka.FlinkKafkaProducer010.invokeInternal(FlinkKafkaProducer010.java:301)
	at org.apache.flink.streaming.connectors.kafka.FlinkKafkaProducer010.invoke(FlinkKafkaProducer010.java:404)
	at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:41)
	at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:206)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.run(OneInputStreamTask.java:69)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:263)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:702)
	at java.lang.Thread.run(Thread.java:748)
```

Any ideas?

This is how I use the `AvroBuilderKeyedSerializationSchema`:
```java
    public static <T extends AvroBuilder> SinkFunction<T> produceAvroToKafka(Class cls) {
        return new FlinkKafkaProducer010<T>(
                T.getTopicName(cls),
                new AvroBuilderKeyedSerializationSchema(Config.DEV.schemaProps()),
                Config.DEV.kafkaProps()
        );
```
`Config.java`:
```java
public enum Config {

    PROD("http://schema-registry:8082", "kafka:9092", "stcs.cep"),
    DEV("http://host:8082", "host:9092", "stcs.cep");

    private Map<String, String> schemaProps;
    private Properties kafkaProps;


    Config(String schemaRegUrl, String bootstrapServer, String groupID) {

        this.schemaProps = new HashMap<String, String>();
        this.kafkaProps  = new Properties();


        this.schemaProps.put("schema.registry.url", schemaRegUrl);
        this.kafkaProps.put("bootstrap.servers", bootstrapServer);
        this.kafkaProps.put("group.id", groupID);
    }

    public Map<String, String> schemaProps() {
        return schemaProps;
    }

    public Properties kafkaProps() {
        return kafkaProps;
    }
}
```

**Comment by smueller18** [comment]
Fixed by 830efc0
