### ISSUE TITLE
java.io.NotSerializableException: kafka.utils.VerifiableProperties

### ISSUE THREAD

**Issue by wipatrick** [smueller18/flink-serialization#2]
Get an error message when running my code:

```java
        Properties schemaProps = new Properties();
        schemaProps.put("schema.registry.url", "http://w-stcs-services:8020");
        VerifiableProperties vProps = new VerifiableProperties(schemaProps);

        SchemaRegistryKeyedDeserializationSchema deserializationSchema = new SchemaRegistryKeyedDeserializationSchema(vProps);

        DataStream<GenericKeyValueRecord> dataStream = env
                .addSource(new FlinkKafkaConsumer010<>(topic, deserializationSchema, FlinkUtils.loadProperties("/kafka.properties")))
                .assignTimestampsAndWatermarks(new TimeStampExtractor());
```

Here is the error:
```sh
09:03:36,061 INFO  org.apache.flink.api.java.typeutils.TypeExtractor             - class com.github.smueller18.flink.serialization.GenericKeyValueRecord is not a valid POJO type
Exception in thread "main" org.apache.flink.api.common.InvalidProgramException: The implementation of the FlinkKafkaConsumer09 is not serializable. The object probably contains or references non serializable fields.
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:100)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.clean(StreamExecutionEnvironment.java:1539)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1451)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1395)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1377)
	at de.hska.stcs.cep.Utils.FlinkUtils.consumeFromKafka(FlinkUtils.java:80)
	at de.hska.stcs.cep.FlinkProgram.run(FlinkProgram.java:47)
	at de.hska.stcs.cep.FlinkProgram.main(FlinkProgram.java:93)
Caused by: java.io.NotSerializableException: kafka.utils.VerifiableProperties
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:317)
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:81)
	... 7 more
```

**Comment by whipit** [comment]
which version did this change get into?

**Comment by smueller18** [comment]
It was version 0.2
